language: node_js #選擇語言

node_js:
  - 9

cache:
  directories:
    - "node_modules"

install:
  - npm install -g gulp-cli
  - yarn

#要執行的程式
script:
  - gulp clean
  - gulp build
  - gulp images

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local-dir: dist
  target-branch: master
  email: jd615645@gmail.com
  name: jd615645
  on:
    branch: master

notifications:
  email:
    on_failure: always

branches:
  only:
    - master
