language: node_js #選擇語言

node_js:
  - 12

cache:
  directories:
    - "node_modules"

install:
  - npm install -g gulp-cli
  - npm install

#要執行的程式
script:
  - gulp prod
  - cp CNAME dist

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local-dir: dist
  email: jd615645@gmail.com
  name: jd615645
  on:
    branch: master

notifications:
  email:
    on_failure: always

branches:
  only:
    - master
