name: bestcase
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      USER_NAME   : jd615645
      USER_EMAIL  : jd615645@gmail.com
      PUBLISH_DIR : ./dist

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          check-latest: true

      - name: Install NPM dependencies
        run: npm install

      - name: Install Gulp CLI
        run: npm install -g gulp-cli

      - name: Build gulp
        run: gulp prod

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.DEPLOY_GHPAGE_TOKEN }}
          publish_dir: ./dist
          cname: bestcase.com.tw
          user_name: ${{ env.USER_NAME }}
          user_email: ${{ env.USER_EMAIL }}